### PR TITLE
Update bibliography.md

### PR DESCRIPTION
**Pull request by sharronrush**
Added recent NY Times article by Ted Kennedy Jr.

### CODE REVIEW

**Comment by yatil** [comment]
@w3c/wai-eo-planning Do we need to have group review for those additions to the bibliography?

**Comment by slhenry** [comment]
https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Process_for_Minor_Changes

**Comment by yatil** [comment]
Okay, so we consider this a minor change. That’s ok for me. Let’s just merge and put the FYI stuff into motion then :-)

**Comment by slhenry** [comment]
Yup, for EO-Plan to agree on, then Chairs/Editor to implement. :-)

**Comment by slhenry** [comment]
ftr +1 from me

**Comment by slhenry** [comment]
approved by Chairs & Staff Contact.

Sharron will inform EOWG for review per https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Process_for_Minor_Changes

**Pull request merged**
