### PR TITLE
French version

### PR DESCRIPTION
**Pull request by notabene**
(sorry to have taken so long, I had forgotten to PR)

### CODE REVIEW

**Comment by slhenry** [comment]
/me skims and doesn't see  anything that needs her attention.

Thanks for your patience @notabene , as yatil and I juggle multiple priorities. (After spending *lots* and *lots* of time on translations for a few months, we had to put some things higher priority for a while.)

We do very much value your contributions to translations!

**Comment by notabene** [comment]
> We do very much value your contributions to translations!

And I value working with you people :)

**Comment by notabene** [comment]
@yatil Is there anything I have to do after all this? Or is it good as is?

**Comment by yatil** [comment]
@notabene I am fixing some technical things at the moment. Nothing for you to do here :-) 

I _think_ @slhenry says it’s ok to go, I’ll publish it once I get final confirmation.

**Pull request merged**
