### PR TITLE
+ page contents

### PR DESCRIPTION
**Pull request by slhenry**

### CODE REVIEW

**Comment by sharronrush** [comment]
Not feeling it to be necessary but no strong objection.

**Comment by slhenry** [comment]
I found myself wanting to jump to a specific section. And with redesign we decided to have in-page contents on most pages.

Now I see that including only h2s in the page contents list, it doesn't include the sections that I want to jump to. (Sorry I missed that those weren't h2s with my original pull request.)

So I propose **_one_** of the following options:
* Including h2 and h3 in the pages contents (which we do in some other documents) with
{::options toc_levels="2,3" /}
* Change the h3s to h2s
* In the Summary, link the bold words to the h3s and then the page contents

Above is order of my preference (that is, I prefer the first); however, I don't feel strongly and I'm fine with editors choice.

@sharronrush

**Comment by yatil** [comment]
@slhenry Might be good to open an issue so it is not overlooked.

**Comment by sharronrush** [comment]
Good, I am fine with linking to h3s

**Pull request merged**
